### PR TITLE
Include Message+ in LG Exalt

### PR DESCRIPTION
**Pull request by FliphoneBochur**
Changed "E-mail" to "Email" and added removing Message+ for LG Exalt
A possible issue would be that the user doesn't understand the not installed for 0 message, so I prompted to ignore it.

### CODE REVIEW

**Comment by SZRabinowitz** [comment]
Regarding your change in language, E-mail is not necessarily incorrect.

"E-mail and email are both correct ways to spell the same word. The issue of the hyphen (or lack thereof) in e-mail is still far from being settled. Different style guides prefer one spelling over the other, so if you need to follow one make sure you use the spelling it prescribes." (grammarly.com).

Regarding your fix for the Exalt Messages package, can you revise it so the user doesn't see a Failure output at all? Thanks

Biden2020Prez

**Comment by FliphoneBochur** [comment]
I understand where you are coming from in regard to the spelling of, "Email," but I feel that since on these phones (The VN220, UN220, L125DL) the app goes by the name, "Email," I would think that that's how it should be spelled in this program. Thank you for your time!

FliphoneBochur

**Comment by SZRabinowitz** [comment]
> I understand where you are coming from in regard to the spelling of, "Email," but I feel that since on these phones (The VN220, UN220, L125DL) the app goes by the name, "Email," I would think that that's how it should be spelled in this program. Thank you for your time!
> 
> FliphoneBochur

Wow. Indeed you are correct that the e-mail apps are registered in the manifest as "Email", so I must agree with that change.
Please update the commands for removing messaging to return without output, and add an echo statement that the app has been uninstalled.


I appreciate your contributions,
Biden2020Prez

**Comment by FliphoneBochur** [comment]
I will work on that and add it to my pull request. When I have modified it, I will let you know. Thank you!

FliphoneBochur

**Comment by FliphoneBochur** [comment]
I have just fixed that issue by running `cls` after each app uninstall followed by a success message. I have also cleaned up the code a bit more and removed the unnecessary `package installer` label. If you would want to add an option to disable the package installer, I would recommend running `adb shell pm disable-user --user 0 com.android.defcontainer` as uninstalling or disabling the actual package installer would probably damage the phone. Thank you!

FliphoneBochur

**Comment by SZRabinowitz** [comment]
The package installer label was added in a commit and removed very shortly thereafter when my phone wouldnt boot up. I left it in the code in case someone like you wants to pick it up. 

I'd rather not clear the console after removing the apps. [This example](https://ss64.com/nt/move.html#:~:text=Quiet%20move%2C%20no%20feedback%20on%20screen%3A%0AMOVE%20oldfile.wp%20newfile.doc%20%3Enul) shows how to block output from a command.

**Comment by FliphoneBochur** [comment]
I just added the `>nul` parameter to those uninstall commands. Once I was editing the code, I tidied up a few things to keep with the same code style throughout the program, removed the `-k` parameters from the uninstalling app commands (so there's no unnecessary data left on the device, and added in a new option to disable app installation (by disabling `defcontainer`). Do you think these changes are beneficial to the program? Thank you!

FliphoneBochur

**Comment by SZRabinowitz** [comment]
Hmm... I know apps4flip.com always leaves the -k. Do you know for sure it's not a problem to remove it?

DIsabling installtion is good. I will need to test it to make sure, but I think it will be fine

**Comment by FliphoneBochur** [comment]
You might want to look at [this](https://forums.apps4flip.com/d/881/4).
Also in the adb documentation: 
>  uninstall [-k] PACKAGE
     remove this app package from the device
     **'-k': keep the data and cache directories**

**Comment by SZRabinowitz** [comment]
Yes, I am well aware of the -k arguement. 

I am referencing Apps4Flip specifically because they did a lot of work on the phones that this tool is geared towards. 

Regarding the user from Apps4Flip Forums that you linked to, he seems to be referring to 3rd party sideloaded apps. 

Additionally, [XDA Developers](https://www.xda-developers.com/uninstall-carrier-oem-bloatware-without-root-access/#:~:text=pm%20uninstall%20%2Dk%20%2D%2Duser%200%20NameOfPackage) seems to suggest that using the `k` variable is good practice for removing system apps. 

[Similar proofs](https://www.techmesto.com/uninstall-pre-installed-apps-from-android-phone/#:~:text=pm%20uninstall%20%2Dk%20%2D%2Duser%200%20package%20name) [can be found](https://medium.com/@ismaeltovar/how-to-delete-android-system-apps-and-bloatware-using-adb-no-root-32d588fa666#:~:text=Once%20there%2C%20run-,pm%20uninstall%20%2Dk%20%2D%2Duser%200%20package.name,-replacing%20package.name) [on many](https://www.maketecheasier.com/uninstall-system-apps-without-root-android/#:~:text=pm%20uninstall%20%2Dk%20%2D%2Duser%200%20package%2Dname) [other](https://droidwin.com/remove-uninstall-bloatware-apps-from-android-via-adb-commands/#:~:text=pm%20uninstall%20%2Dk%20%2D%2Duser%200%20%3Cpackage%20name%3E) [sites](https://forum.xda-developers.com/t/uninstall-bloatwares-no-root.4321387/)

**Comment by FliphoneBochur** [comment]
Ok. So I see where you are coming from. I added the parameter back in. Thank you!

FliphoneBochur

**Comment by SZRabinowitz** [comment]
Okay. Now I will run the batch script locally to make sure there are no issues. And then I will merge this request.

**Comment by FliphoneBochur** [comment]
I was about to ask you if you can merge the pull request, but I've just been informed that the hotspot still works even when `com.lge.hotspotlauncher` is uninstalled, so I have removed that option from the code. If you would be able to merge the commits in the near future, I would appreciate it. Thank you!

FliphoneBochur

**Comment by SZRabinowitz** [comment]
Okay, great work.

**Pull request merged**
